name: Build HT Audio 98 Plugins
on: [push, pull_request]
jobs:
  build:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, macos-latest]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Build Plugins
        run: |
          cmake -B build -DCMAKE_BUILD_TYPE=Release
          cmake --build build --config Release
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: HT-Audio-98-Plugins-${{ matrix.os }}
          path: |
            build/**/*.vst3
            build/**/*.component
